export default ({ title, fullText, time, author, authorValueOptions }) => [
  {
    id: "title",
    type: "text",
    name: "title",
    placeholder: "Short text (5-50 chars)",
    label: "Short text",
    minSymbols: 5,
    maxSymbols: 50,
    required: true,
    value: title,
  },
  {
    id: "fulltext",
    type: "textarea",
    name: "fullText",
    placeholder: "Full text",
    label: "Full text",
    minSymbols: 5,
    maxSymbols: 1000,
    required: true,
    value: fullText,
  },
  {
    id: "time",
    type: "text",
    name: "time",
    label: "Date and time",
    placeholder: "dd-MM-yyyy hh:mm",
    validator: "dateTimeByCharWithInvisibleMask",
    value: time,
  },
  {
    id: "author",
    type: "search",
    name: "author",
    label: "Author",
    value: author,
    valueOptions: authorValueOptions,
  },
];
