name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com/'
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com:_authToken=${{ GITHUB_TOKEN }}" > ~/.npmrc
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "devocean-client" #Must be unique in Heroku
          heroku_email: "lo.ma200018@gmail.com"
          healthcheck: "http://devocean-client.herokuapp.com"
